export interface Product {
  slug: string;
  name: string;
  brand: string;
  origin: string;
  category: string;
  price: number;
  wholesalePriceL1: number;
  wholesalePriceL2: number;
  costPrice: number;
  rating: number;
  reviewCount: number;
  badge?: string;
  description: string;
  details: string[];
  images: string[];
  stock: number;
}

export const PRODUCTS: Product[] = [
  {
    slug: "ishiya-white-chocolate",
    name: "白之戀人 24件入",
    brand: "石屋製菓 Ishiya",
    origin: "北海道",
    category: "hokkaido",
    price: 388,
    wholesalePriceL1: 298,
    wholesalePriceL2: 268,
    costPrice: 200,
    rating: 4.8,
    reviewCount: 32,
    badge: "人氣熱賣",
    description:
      "來自北海道的經典手信。白之戀人採用北海道新鮮牛油製作，夾著白朱古力，入口即溶。每件獨立包裝，送禮自用皆宜。",
    details: [
      "內容：白之戀人 24件",
      "產地：日本北海道",
      "賞味期限：2025年9月",
      "保存方法：避免高溫潮濕，28°C以下保存",
    ],
    images: [],
    stock: 50,
  },
  {
    slug: "tokyo-matcha-gift",
    name: "東京抹茶禮盒",
    brand: "京都宇治",
    origin: "東京",
    category: "tokyo",
    price: 298,
    wholesalePriceL1: 238,
    wholesalePriceL2: 218,
    costPrice: 160,
    rating: 4.6,
    reviewCount: 28,
    badge: "新上市",
    description:
      "嚴選京都宇治抹茶，配以東京職人製作的和菓子。一盒嚐盡春日氣息。",
    details: [
      "內容：抹茶粉 50g + 和菓子 8件",
      "產地：日本京都・東京",
      "賞味期限：2025年11月",
    ],
    images: [],
    stock: 35,
  },
  {
    slug: "kyoto-wagashi",
    name: "京都和菓子禮盒",
    brand: "虎屋",
    origin: "京都",
    category: "kyoto",
    price: 458,
    wholesalePriceL1: 368,
    wholesalePriceL2: 338,
    costPrice: 250,
    rating: 4.7,
    reviewCount: 18,
    badge: "季節限定",
    description:
      "創業500年の虎屋製和菓子禮盒。每一件都由職人親手製作，傳遞京都的四季之美。",
    details: [
      "內容：和菓子 12件 (4種口味各3件)",
      "產地：日本京都",
      "賞味期限：2025年8月",
    ],
    images: [],
    stock: 20,
  },
  {
    slug: "hokkaido-royce",
    name: "Royce 朱古力禮盒",
    brand: "Royce",
    origin: "北海道",
    category: "hokkaido",
    price: 268,
    wholesalePriceL1: 208,
    wholesalePriceL2: 188,
    costPrice: 140,
    rating: 4.9,
    reviewCount: 45,
    badge: "人氣熱賣",
    description: "北海道 Royce 的生朱古力系列。使用北海道新鮮忌廉，口感絲滑細膩。",
    details: [
      "內容：生朱古力 20件 (2種口味各10件)",
      "產地：日本北海道",
      "賞味期限：2025年7月",
    ],
    images: [],
    stock: 0,
  },
  {
    slug: "hakodate-sweets",
    name: "函館甜品禮盒",
    brand: "函館菓子工房",
    origin: "北海道",
    category: "hokkaido",
    price: 328,
    wholesalePriceL1: 258,
    wholesalePriceL2: 238,
    costPrice: 180,
    rating: 4.5,
    reviewCount: 12,
    description: "函館人氣甜品店限定禮盒。包含芝士蛋糕、布甸及曲奇，一次過品嚐函館的味道。",
    details: [
      "內容：芝士蛋糕 1個 + 布甸 2個 + 曲奇 6件",
      "產地：日本北海道函館",
    ],
    images: [],
    stock: 15,
  },
  {
    slug: "seasonal-sakura",
    name: "季節限定・櫻花禮盒",
    brand: "多間名店合作",
    origin: "東京",
    category: "seasonal",
    price: 528,
    wholesalePriceL1: 428,
    wholesalePriceL2: 398,
    costPrice: 300,
    rating: 4.9,
    reviewCount: 8,
    badge: "季節限定",
    description: "春季限定櫻花主題禮盒。集合東京多間名店的櫻花味甜品，期間限定發售。",
    details: [
      "內容：櫻花餅 4件 + 櫻花朱古力 6件 + 櫻花曲奇 6件",
      "產地：日本東京",
    ],
    images: [],
    stock: 10,
  },
  {
    slug: "afternoon-tea-cold-brew-iced-tea",
    name: "Afternoon tea living Cold Brew Iced Tea 冷泡冰茶",
    brand: "Afternoon tea living",
    origin: "日本",
    category: "snacks",
    price: 108,
    wholesalePriceL1: 88,
    wholesalePriceL2: 78,
    costPrice: 60,
    rating: 4.5,
    reviewCount: 12,
    description: "Afternoon tea living推出製作簡單又美味的冷泡冰茶！提供多種茶和水果口味組合供您享用。",
    details: ["產地：日本", "多種口味可選"],
    images: [],
    stock: 30,
  },
  {
    slug: "densundo-shrimp-crackers",
    name: "でんすん堂 蝦餅(牛油果芝士味/明太子芝士味)",
    brand: "でんすん堂",
    origin: "日本",
    category: "snacks",
    price: 55,
    wholesalePriceL1: 45,
    wholesalePriceL2: 40,
    costPrice: 30,
    rating: 4.3,
    reviewCount: 8,
    description: "將日本傳統蝦仙貝的清脆與現代濃郁的西式風味完美結合。",
    details: ["口味：牛油果芝士 / 明太子芝士", "產地：日本"],
    images: [],
    stock: 50,
  },
  {
    slug: "711-butter-state-strawberry-cookie",
    name: "7-11 x BUTTER STATE's 士多啤梨味火山曲奇",
    brand: "BUTTER STATE's",
    origin: "日本",
    category: "snacks",
    price: 36,
    wholesalePriceL1: 28,
    wholesalePriceL2: 25,
    costPrice: 18,
    rating: 4.2,
    reviewCount: 15,
    description: "濃鬱的草莓巧克力淋面，相當於40%的新鮮草莓，慷慨地淋在餅乾上。",
    details: ["內容：3塊", "產地：日本"],
    images: [],
    stock: 100,
  },
  {
    slug: "711-sbt-strawberry-cream-sandwich",
    name: "7-11 x SBT 士多啤梨奶油夾心餅",
    brand: "Sugar Butter Tree",
    origin: "日本",
    category: "snacks",
    price: 35,
    wholesalePriceL1: 28,
    wholesalePriceL2: 25,
    costPrice: 18,
    rating: 4.1,
    reviewCount: 10,
    description: "草莓巧克力濃鬱香醇，草莓含量高達45%！",
    details: ["內容：3塊", "產地：日本"],
    images: [],
    stock: 100,
  },
  {
    slug: "sugar-butter-tree-muscat-grape-set",
    name: "|夏季限定| SUGAR BUTTER TREE 麝香提子朱古力味+原味奶油夾心餅",
    brand: "Sugar Butter Tree",
    origin: "日本",
    category: "seasonal",
    price: 170,
    wholesalePriceL1: 140,
    wholesalePriceL2: 125,
    costPrice: 95,
    rating: 4.7,
    reviewCount: 6,
    badge: "夏季限定",
    description: "融入日本國產麝香葡萄汁的乳白巧克力，夾在五種香濃穀物麵團之間。",
    details: ["內容：麝香提子味 + 原味各一盒", "產地：日本", "夏季限定"],
    images: [],
    stock: 20,
  },
  {
    slug: "sugar-butter-tree-muscat-grape-single",
    name: "|夏季限定| SUGAR BUTTER TREE 麝香提子朱古力味奶油夾心餅",
    brand: "Sugar Butter Tree",
    origin: "日本",
    category: "seasonal",
    price: 98,
    wholesalePriceL1: 80,
    wholesalePriceL2: 72,
    costPrice: 55,
    rating: 4.6,
    reviewCount: 5,
    badge: "夏季限定",
    description: "融入日本國產麝香葡萄汁的乳白巧克力，炎熱季節搭配冰茶最合適。",
    details: ["內容：麝香提子味", "產地：日本", "夏季限定"],
    images: [],
    stock: 25,
  },
  {
    slug: "711-sumire-sapporo-miso-ramen",
    name: "日本7-11 Sumire 札幌濃鬱味噌拉麵",
    brand: "7-11",
    origin: "日本",
    category: "snacks",
    price: 48,
    wholesalePriceL1: 38,
    wholesalePriceL2: 34,
    costPrice: 25,
    rating: 4.4,
    reviewCount: 22,
    description: "Threads大推！湯底勁濃，超掛麵，麵條又煙韌，神還原拉麵！",
    details: ["容量：145g", "產地：日本"],
    images: [],
    stock: 60,
  },
  {
    slug: "drooly-honey-cheese-chocolate-sandwich",
    name: "DROOLY 蜂蜜芝士朱古力夾心餅",
    brand: "DROOLY",
    origin: "日本",
    category: "snacks",
    price: 110,
    wholesalePriceL1: 88,
    wholesalePriceL2: 78,
    costPrice: 60,
    rating: 4.5,
    reviewCount: 14,
    description: "香濃的卡門貝爾芝士淋上厚厚一層蜂蜜，芝士和蜂蜜的甜香交織。",
    details: ["產地：日本", "多種規格可選"],
    images: [],
    stock: 40,
  },
  {
    slug: "sabrina-flower-cream-mille-feuille",
    name: "薫るバターsabrina 花朵奶油千層酥",
    brand: "sabrina",
    origin: "日本",
    category: "snacks",
    price: 110,
    wholesalePriceL1: 88,
    wholesalePriceL2: 78,
    costPrice: 60,
    rating: 4.6,
    reviewCount: 18,
    description: "嚴選世界各地優質奶油，人氣No.1推薦花朵奶油千層酥。",
    details: ["產地：日本", "多種規格可選"],
    images: [],
    stock: 35,
  },
  {
    slug: "drooly-honey-cheese-feuilletine",
    name: "DROOLY 蜂蜜芝士費南雪【人氣】",
    brand: "DROOLY",
    origin: "日本",
    category: "snacks",
    price: 98,
    wholesalePriceL1: 78,
    wholesalePriceL2: 68,
    costPrice: 50,
    rating: 4.7,
    reviewCount: 20,
    badge: "人氣",
    description: "芝士淋上厚厚一層蜂蜜，蜂蜜芝士的甜香交織，溫柔成熟的風味。",
    details: ["產地：日本", "多種規格可選"],
    images: [],
    stock: 45,
  },
  {
    slug: "pista-tokyo-pistachio-sandwich-cookies",
    name: "現貨！PISTA &TOKYO 開心果夾心餅乾5件裝",
    brand: "PISTA & TOKYO",
    origin: "東京",
    category: "tokyo",
    price: 120,
    wholesalePriceL1: 98,
    wholesalePriceL2: 88,
    costPrice: 68,
    rating: 4.8,
    reviewCount: 25,
    badge: "現貨",
    description: "開心果甜品專賣店招牌產品！五層夾心餅乾，鹹味開心果餅乾配開心果朱古力。",
    details: ["內容：5件裝", "產地：日本東京"],
    images: [],
    stock: 30,
  },
  {
    slug: "royce-pistachio-chocolate-bar",
    name: "ROYCE 開心果朱古力BAR",
    brand: "Royce",
    origin: "北海道",
    category: "hokkaido",
    price: 138,
    wholesalePriceL1: 110,
    wholesalePriceL2: 98,
    costPrice: 75,
    rating: 4.6,
    reviewCount: 8,
    badge: "期間限定",
    description: "牛奶巧克力包裹整顆鹹味烤開心果，配上蔓越莓乾、草莓乾、餅乾碎。",
    details: ["產地：日本北海道", "期間限定"],
    images: [],
    stock: 15,
  },
  {
    slug: "yoku-moku-matcha-egg-rolls",
    name: "【季節限定】Yoku Moku蛋卷 - 宇治抹茶味",
    brand: "Yoku Moku",
    origin: "東京",
    category: "seasonal",
    price: 218,
    wholesalePriceL1: 178,
    wholesalePriceL2: 158,
    costPrice: 120,
    rating: 4.8,
    reviewCount: 12,
    badge: "季節限定",
    description: "Yoku Moku經典蛋卷，宇治抹茶味季節限定，送禮首選。",
    details: ["產地：日本東京", "季節限定"],
    images: [],
    stock: 10,
  },
  {
    slug: "sugar-butter-tree-charcoal-chocolate",
    name: "SUGAR BUTTER TREE 炭火朱古力味<冬季限定>",
    brand: "Sugar Butter Tree",
    origin: "日本",
    category: "seasonal",
    price: 98,
    wholesalePriceL1: 78,
    wholesalePriceL2: 68,
    costPrice: 50,
    rating: 4.5,
    reviewCount: 10,
    badge: "冬季限定",
    description: "每年最受歡迎口味回歸！奢華夾心餅，淋上濃鬱的「炭烤巧克力」。",
    details: ["產地：日本", "冬季限定"],
    images: [],
    stock: 0,
  },
];
